# Generated by Django 4.1.5 on 2023-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
